# Generated by Django 3.0.4 on 2020-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WduserAuthuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.IntegerField()),
                ('role_type', models.PositiveIntegerField()),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('headimg', models.CharField(blank=True, max_length=200, null=True)),
                ('active_code', models.CharField(blank=True, max_length=20, null=True)),
                ('active_code_valid', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=400, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dedicated_link', models.CharField(blank=True, max_length=60, null=True)),
                ('age_id', models.IntegerField(blank=True, null=True)),
                ('seniority_id', models.IntegerField(blank=True, null=True)),
                ('gender_id', models.IntegerField(blank=True, null=True)),
                ('marriage_id', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('rank_id', models.IntegerField(blank=True, null=True)),
                ('sequence_id', models.IntegerField(blank=True, null=True)),
                ('politics_id', models.IntegerField(blank=True, null=True)),
                ('education_id', models.IntegerField(blank=True, null=True)),
                ('importlot', models.IntegerField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'wduser_authuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WduserOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=30, null=True)),
                ('org_level1', models.CharField(blank=True, max_length=150, null=True)),
                ('org_level2', models.CharField(blank=True, max_length=150, null=True)),
                ('org_level3', models.CharField(blank=True, max_length=150, null=True)),
                ('org_level4', models.CharField(blank=True, max_length=150, null=True)),
                ('org_level5', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'wduser_org',
                'managed': False,
            },
        ),
    ]
